In [2]:
import os
import pandas as pd

In [ ]:
dirPath = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/cleanData/"
outdir = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/CARDInputs/"

keys = ['ND', 'HFD8', 'HFD14']

for key in keys:
    
    clusterPath = f"{dirPath}{key}_clusters.pq"
    cdf = pd.read_parquet(clusterPath)
    cdf['sampleInfo'] = key
    cdf['cellId'] = cdf['cellId'].str.replace("-", ".")
    cdf = cdf.drop(['clusterId'], axis=1)
    
    rnaPath = f"{dirPath}{key}_rna.pq"
    rdf = pd.read_parquet(rnaPath)
    
    sptPath = f"{dirPath}{key}_spt.pq"
    sdf = pd.read_parquet(sptPath)
    
    xyPath = f"{dirPath}{key}_coords.pq"
    xydf = pd.read_parquet(xyPath)
    xydf.index = xydf.index.str.replace("-", ".")
    
    # transpose the rna and spt datasets
    rdf = rdf.T
    sdf = sdf.T
    
    # filter out genes not expressed in both
    rnaGenes = list(rdf.index)
    sptGenes = list(sdf.index)
    
    rdf = rdf[rdf.index.isin(sptGenes)]
    sdf = sdf[sdf.index.isin(rnaGenes)]
    
    # some string ops
    rdf.columns = [x.replace("-", ".") for x in rdf.columns]
    
    # outpaths
    clusterPath = f"{outdir}{key}_clusters.csv"
    rnaPath = f"{outdir}{key}_rna.csv"
    sptPath = f"{outdir}{key}_spt.csv"
    xyPath = f"{outdir}{key}_coords.csv"
    
    cdf.to_csv(clusterPath, index=False)
    rdf.to_csv(rnaPath, index=True)
    sdf.to_csv(sptPath, index=True)
    xydf.to_csv(xyPath, index=True)
        
    print(key, cdf.shape, rdf.shape, sdf.shape, xydf.shape)

ND (1261, 3) (12490, 1261) (12490, 2035) (2035, 2)
HFD8 (6123, 3) (13768, 6123) (13768, 3392) (3392, 2)

In [34]:
cdf.head()

               cellId     cellType sampleInfo
0  AAACGAACAGCAGTAG.1      B cells         ND
1  AAAGAACGTCTACAGT.1  Macrophages         ND
2  AAAGAACTCCTCGCAT.1  Macrophages         ND
3  AAAGGGCGTTAGGGTG.1  Macrophages         ND
4  AACAAAGAGTATAGGT.1    Monocytes         ND

In [35]:
rdf.head()

,AAACGAACAGCAGTAG.1,AAAGAACGTCTACAGT.1,AAAGAACTCCTCGCAT.1,AAAGGGCGTTAGGGTG.1,AACAAAGAGTATAGGT.1,AACAAAGCACCGGCTA.1,AACAAAGGTTCACGAT.1,AACAAAGTCAAGCTGT.1,AACAAAGTCTTAGCTT.1,AACAACCGTTGACTAC.1,...,TTTGACTCAACTCGAT.1,TTTGACTGTCGTGCCA.1,TTTGACTTCTGGAAGG.1,TTTGGAGCACATCCCT.1,TTTGGAGCATCGTCCT.1,TTTGGTTAGAAGATCT.1,TTTGGTTGTACCGGAA.1,TTTGGTTTCCTTACCG.1,TTTGTTGAGCTAAGTA.1,TTTGTTGTCTGAGGCC.1
MRPL15,0.0,0.000000,0.00000,0.751568,0.691501,0.000000,0.000000,0.000000,1.290813,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.473716,0.000000,0.746363,0.000000,0.000000
LYPLA1,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,1.463523,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,1.126363,0.388943,0.000000,0.000000
TCEA1,0.0,1.540236,0.00000,0.000000,0.000000,0.000000,1.463523,1.780187,0.000000,1.316010,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.583538,1.289620,0.000000
ATP6V1H,0.0,0.000000,0.00000,0.751568,0.000000,0.000000,0.000000,0.000000,1.290813,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.147103,0.000000,1.364714
RB1CC1,0.0,1.540236,1.16732,0.000000,0.691501,0.619184,0.000000,0.000000,0.000000,0.860464,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.668261,0.839713,0.000000