In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# dirPath = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/cleanData/"
# outdir = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/CARDInputs/"

# keys = ['ND', 'HFD8', 'HFD14']

# for key in keys:
    
#     clusterPath = f"{dirPath}{key}_clusters.pq"
#     cdf = pd.read_parquet(clusterPath)
#     cdf['sampleInfo'] = key
#     cdf['cellId'] = cdf['cellId'].str.replace("-", ".")
#     cdf = cdf.drop(['clusterId'], axis=1)
    
#     rnaPath = f"{dirPath}{key}_rna.pq"
#     rdf = pd.read_parquet(rnaPath)
#     rdf.index = rdf.index.str.replace("-", ".")
    
#     sptPath = f"{dirPath}{key}_spt.pq"
#     sdf = pd.read_parquet(sptPath)
    
#     xyPath = f"{dirPath}{key}_coords.pq"
#     xydf = pd.read_parquet(xyPath)
#     xydf.index = xydf.index.str.replace("-", ".")
    
#     # remove filtered cells
#     rdf = rdf[rdf.index.isin(cdf['cellId'])]
    
#     # transpose the rna and spt datasets
#     rdf = rdf.T
#     sdf = sdf.T
    
#     # filter out genes not expressed in both
#     rnaGenes = list(rdf.index)
#     sptGenes = list(sdf.index)
    
#     rdf = rdf[rdf.index.isin(sptGenes)]
#     sdf = sdf[sdf.index.isin(rnaGenes)]
    
#     # outpaths
#     clusterPath = f"{outdir}{key}_clusters.csv"
#     rnaPath = f"{outdir}{key}_rna.csv"
#     sptPath = f"{outdir}{key}_spt.csv"
#     xyPath = f"{outdir}{key}_coords.csv"
    
#     cdf.to_csv(clusterPath, index=False)
#     rdf.to_csv(rnaPath, index=True)
#     sdf.to_csv(sptPath, index=True)
#     xydf.to_csv(xyPath, index=True)
        
#     print(key, cdf.shape, rdf.shape, sdf.shape, xydf.shape)

In [3]:
# """ build macrophage subtype inputs """

# sfPath = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/scanpy/macrophageSubtypes.csv"
# dirPath = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/cleanData/"
# outdir = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/CARDInputs/"

# sf = pd.read_csv(sfPath)
# sf['cellId'] = sf['cellId'].str.replace("-", ".")

# # keep = [
# #     'Stromal cells',
# #     'Monocytes',
# #     'Macrophages'
# # ] 

# keys = ['ND', 'HFD8', 'HFD14']

# for key in keys:
#     clusterPath = f"{dirPath}{key}_clusters.pq"
#     cdf = pd.read_parquet(clusterPath)
#     cdf['sampleInfo'] = key
#     cdf['cellId'] = cdf['cellId'].str.replace("-", ".")
#     cdf = cdf.drop(['clusterId'], axis=1)
    
#     subtypes = sf[sf['key'] == key]
    
#     cdf = pd.merge(cdf, subtypes,
#                    how='left',
#                    left_on='cellId',
#                    right_on='cellId')
    
#     # cdf = cdf[cdf['cellType_x'].isin(keep)]
#     cdf['cellType'] = np.where(cdf['subtypeId'].isna(), cdf['cellType_x'], cdf['subtypeId'])
#     cdf = cdf[['cellId', 'cellType', 'sampleInfo']]
    
#     rnaPath = f"{dirPath}{key}_rna.pq"
#     rdf = pd.read_parquet(rnaPath)
#     rdf.index = rdf.index.str.replace("-", ".")
    
#     sptPath = f"{dirPath}{key}_spt.pq"
#     sdf = pd.read_parquet(sptPath)
    
#     xyPath = f"{dirPath}{key}_coords.pq"
#     xydf = pd.read_parquet(xyPath)
#     xydf.index = xydf.index.str.replace("-", ".")
    
#     # remove filtered cells
#     rdf = rdf[rdf.index.isin(cdf['cellId'])]
    
#     # transpose the rna and spt datasets
#     rdf = rdf.T
#     sdf = sdf.T
    
#     # filter out genes not expressed in both
#     rnaGenes = list(rdf.index)
#     sptGenes = list(sdf.index)
    
#     rdf = rdf[rdf.index.isin(sptGenes)]
#     sdf = sdf[sdf.index.isin(rnaGenes)]
    
#     # outpaths
#     clusterPath = f"{outdir}{key}_macrophage_clusters.csv"
#     rnaPath = f"{outdir}{key}_macrophage_rna.csv"
#     sptPath = f"{outdir}{key}_macrophage_spt.csv"
#     xyPath = f"{outdir}{key}_macrophage_coords.csv"
    
#     cdf.to_csv(clusterPath, index=False)
#     rdf.to_csv(rnaPath, index=True)
#     sdf.to_csv(sptPath, index=True)
#     xydf.to_csv(xyPath, index=True)
        
#     print(key, cdf.shape, rdf.shape, sdf.shape, xydf.shape)
    
#     # break
# print('done')

In [16]:
""" gloabl inputs """

sfPath = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/scanpy/macrophageSubtypes.csv"
dirPath = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/cleanData/"
outdir = "/nfs/turbo/umms-indikar/shared/projects/spatial_transcriptomics/data/CARDInputs/"

sf = pd.read_csv(sfPath)
sf['cellId'] = sf['cellId'].str.replace("-", ".")


keys = ['ND', 'HFD8', 'HFD14']

annotDf = []
rnaDf = None

for key in keys:
    clusterPath = f"{dirPath}{key}_clusters.pq"
    cdf = pd.read_parquet(clusterPath, engine='fastparquet')
    cdf['sampleInfo'] = key
    cdf['cellId'] = cdf['cellId'].str.replace("-", ".")
    cdf = cdf.drop(['clusterId'], axis=1)
    
    subtypes = sf[sf['key'] == key]
    
    cdf = pd.merge(cdf, subtypes,
                   how='left',
                   left_on='cellId',
                   right_on='cellId')
    
    # cdf = cdf[cdf['cellType_x'].isin(keep)]
    cdf['cellType'] = np.where(cdf['subtypeId'].isna(), cdf['cellType_x'], cdf['subtypeId'])
    cdf = cdf[['cellId', 'cellType', 'sampleInfo']]
    # add key to cellId
    cdf['cellId'] = cdf['cellId'] + "_" + cdf['sampleInfo']
    
    
    rnaPath = f"{dirPath}{key}_rna.pq"
    rdf = pd.read_parquet(rnaPath)
    rdf.index = rdf.index.str.replace("-", ".")
    rdf.index = rdf.index.astype(str) + f"_{key}" 

    
    sptPath = f"{dirPath}{key}_spt.pq"
    sdf = pd.read_parquet(sptPath)
    sdf.index = sdf.index.str.replace("-", ".")
    sdf.index = sdf.index.astype(str) + f"_{key}" 
    
    xyPath = f"{dirPath}{key}_coords.pq"
    xydf = pd.read_parquet(xyPath)
    xydf.index = xydf.index.str.replace("-", ".")
    xydf.index = xydf.index.astype(str) + f"_{key}" 

    # remove filtered cells
    rdf = rdf[rdf.index.isin(cdf['cellId'])]
    
    # transpose the rna and spt datasets
    rdf = rdf.T
    sdf = sdf.T
    
    # filter out genes not expressed in both
    rnaGenes = list(rdf.index)
    sptGenes = list(sdf.index)
    
    rdf = rdf[rdf.index.isin(sptGenes)]
    sdf = sdf[sdf.index.isin(rnaGenes)]
    
    # structure the combined RNA dataframes
    if rnaDf is None:
        rnaDf = rdf
    else:
        rnaDf = pd.merge(rnaDf, rdf, 
                         how='left', 
                         right_index=True,
                         left_index=True)

    # structure the annotations
    annotDf.append(cdf)
    
    # save the spatial data
    sptPath = f"{outdir}{key}_global_spt.csv"
    xyPath = f"{outdir}{key}_global_coords.csv"
    
    sdf.to_csv(sptPath, index=True)
    xydf.to_csv(xyPath, index=True)
        
    print(key, cdf.shape, rdf.shape, sdf.shape, xydf.shape)
    
# combine the RNA signatures
annotDf = pd.concat(annotDf)
print(f"{rnaDf.shape=}")
print(f"{annotDf.shape=}")
    
# RNA outpath
rnaPath = f"{outdir}_global_rna.csv"
annotationPath = f"{outdir}_global_clusters.csv"

rnaDf.to_csv(rnaPath, index=True)
annotDf.to_csv(annotationPath, index=True)
print('done')

ND (1261, 3) (31053, 1261) (31053, 2036) (2036, 2)
HFD8 (6123, 3) (31053, 6123) (31053, 3394) (3394, 2)
HFD14 (6436, 3) (31053, 6436) (31053, 1994) (1994, 2)
rnaDf.shape=(31053, 13820)
annotDf.shape=(13820, 3)
done

In [7]:
rnaDf.head()

,AAACGAACAGCAGTAG.1_ND,AAAGAACGTCTACAGT.1_ND,AAAGAACTCCTCGCAT.1_ND,AAAGGGCGTTAGGGTG.1_ND,AACAAAGAGTATAGGT.1_ND,AACAAAGCACCGGCTA.1_ND,AACAAAGGTTCACGAT.1_ND,AACAAAGTCAAGCTGT.1_ND,AACAAAGTCTTAGCTT.1_ND,AACAACCGTTGACTAC.1_ND,...,TTTGGTTTCTCCCATG.1_HFD14,TTTGGTTTCTTGGATG.1_HFD14,TTTGTTGAGGTTATAG.1_HFD14,TTTGTTGAGTCGCCAC.1_HFD14,TTTGTTGGTCCACTTC.1_HFD14,TTTGTTGGTCGTTATG.1_HFD14,TTTGTTGGTTAGGAGC.1_HFD14,TTTGTTGTCACGAACT.1_HFD14,TTTGTTGTCGACCTAA.1_HFD14,TTTGTTGTCTGGGCCA.1_HFD14
XKR4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GM1992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GM37381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RP1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SOX17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
sdf.head()

,AAACATTTCCCGGATT-1,AAACCGGGTAGGTACC-1,AAACCGTTCGTCCAGG-1,AAACCTAAGCAGCCGG-1,AAACCTCATGAAGTTG-1,AAACGGGCGTACGGGT-1,AAACGGTTGCGAACTG-1,AAACTCGGTTCGCAAT-1,AAACTGCTGGCTCCAA-1,AAACTTGCAAACGTAT-1,...,TTGTGAACCTAATCCG-1,TTGTGAGGCATGACGC-1,TTGTGCAGCCACGTCA-1,TTGTGGTGGTACTAAG-1,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTTCACATCCAGG-1,TTGTTTCCATACAACT-1
XKR4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GM1992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GM37381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RP1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SOX17,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
xydf.head()

                                    x            y
AAACATTTCCCGGATT.1_HFD14  1139.783401  1365.804581
AAACCGGGTAGGTACC.1_HFD14   468.056902  1045.415505
AAACCGTTCGTCCAGG.1_HFD14   604.524374  1214.452428
AAACCTAAGCAGCCGG.1_HFD14  1003.708924  1433.743571
AAACCTCATGAAGTTG.1_HFD14   380.369919   960.970730

In [ ]:
cdf.head()

In [ ]:
# cdf.head()

In [ ]:
# rdf.head()